theme = "bootstrap4-blog"
baseURL = "http://nofakingway.com"
languageCod = "en-us"
title = "NOFA Kingway"
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 
enableRobotsTXT = true
publishDir = "docs"

disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

# [Author] # Used in authorbox
#     name = "Mark Stouffer"
#     bio = "Speaking in tech, one of the last refuges of Reason."
#     avatar = "img/avatar.png"

# [Params]
#     subtitle = "A lie is not your aly. It is a liability." # Subtitle of your site. Used in site header
#     description = "Justifying a commitment to fidelity to truth." # Description of your site. Used in meta description
#     opengraph = true # Enable OpenGraph if true
#     readmore = false # Show "Read more" button in list if true
#     leftsidebar = false # Move sidebar to the left side if true
#     authorbox = true # Show authorbox at bottom of pages if true
#     post_navigation = true # Show post navigation at bottom of pages if true
#     postSections = ["post"] # the section pages to show on home page and the "Recent articles" widget
#     #postSections = ["blog", "news"] # alternative that shows more than one section's pages
#     #dateformat = "2006-01-02" # change the format of dates

[permalinks]
  post = "/:year/:month/:title/"
  page = "/:slug/"

[[menu.sidebar]]
  name = "Link 1"
  url = "https://example.com"

[[menu.sidebar]]
  name = "Link 2"
  url = "https://example.org"

# custom navbar menu entry.   See the custom_navbar parameter below for
# details.

#[[menu.navbar]]
#  name = "Link 1"
#  url = "https://example.org"


# Theme variables
#
[params]
  # Site author
  author = "Mark Stouffer"

  # Description/subtitle for homepage (can be Markdown)
  description = "A lie is not your aly. It is a liability."

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # verification string for Google Webmaster Tools
  #google_verify_meta = "BAi57DROASu4b2mkVNA_EyUsobfA7Mq8BmSg7Rn-Zp9"

  # verification string for Bing Webmaster Tools
  #bing_verify_meta = "3DA353059F945D1AA256B1CD8A3DA847"

  # verification string for Yandex Webmaster Tools
  #yandex_verify_meta = "66b077430f35f04a"

  # Optionally display a message about the site's use of cookies, which may be
  # required for your site in the European Union. Set the parameter below to a
  # page where the user can get more information about cookies, either on your
  # site or externally, for example:
  #cookie_consent_info_url = "/cookie-information/"
  #cookie_consent_info_url = "http://cookiesandyou.com"

  # customise the contents of the navbar at the top of the page.  The default
  # behaviour is to list all static pages not in the posts directory. When the
  # parameter below is set to true you will have to manually add entries to the
  # navbar, either by adding the following menu variable to the front matter of
  # the relevant pages
  #   menu = "navbar"
  # or by specifying menu entries in a similar way to the sidebar menu above.
  #custom_navbar = true

  # show sharing icons on pages/posts (default: true)
  #sharingicons = true

  # Display post summaries instead of content in list templates (default: true)
  #truncate = true

  # Disable the use of sub-resource integrity on CSS/JS assets (default: false)
  # Useful if you're using a CDN or other host where you can't control cache headers
  disable_sri = true

  [params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    about = "Justifying a commitment to fidelity to truth."

    # How many posts to show on the sidebar (Default: 5)
    #num_recent_posts = 2

  [params.social]
    # Optional, used for attribution in Twitter cards (ideally not a person
    # for example: nytimes, flickr, NatGeo, etc).
    # See: https://dev.twitter.com/cards/types/summary-large-image
    twitter = "ValueCritic"

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
#DefaultContentLanguage = "en"

# Languages to render
#[languages.en]
#[languages.bg]

# vim: ts=2 sw=2 et
